package by.milavitsky.homework.enums;

public enum  EnumSort {
    ENGINE_POWER, LIFTING_CAPACITY, CAPACITY_OF_PASSENGERS, FUEL_CONSUMPTION, TANK_CAPACITY, MAX_SPEED, WEIGHT, PLANE_TYP, CLASSIFICATION ;
}
