package by.milavitsky.homework.enums;

import by.milavitsky.homework.entity.AbstractPlane;

public enum SortType {
    ENGINE_POWER, LIFTING_CAPACITY, CAPACITY_OF_PASSENGERS, FUEL_CONSUMPTION, TANK_CAPACITY, MAX_SPEED, WEIGHT, PLANE_TYP_WAR, CLASSIFICATION, ENGINE_POWER_REVERSE, LIFTING_CAPACITY_REVERSE, CAPACITY_OF_PASSENGERS_REVERSE, FUEL_CONSUMPTION_REVERSE, TANK_CAPACITY_REVERSE, MAX_SPEED_REVERSE, WEIGHT_REVERSE, PLANE_TYP_CIVILIAN, MAX_SPEED__WEIGHT__LIFTING_CAPACITY;
    /*public String getName(AbstractPlane o1){
        return EnumSort.valueOf(EnumSort.PLANE_TYP_CIVILIAN)
    }*/

}
